services:
  - type: web
    name: lablinq-api
    runtime: dotnet
    plan: free
    buildCommand: cd LabLINQ && dotnet restore && dotnet publish -c Release -o ./publish
    startCommand: cd LabLINQ/publish && dotnet LabLINQ.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ConnectionStrings__MySQLConnection
        sync: false  # Esto requiere que configures la variable manualmente en Render
    healthCheckPath: /swagger
    autoDeploy: true

